title: Abolition and the University
description: A Round Table Discussion — CSA 2021

url: http://sgotzler.github.com/abolition-uni
baseurl: "/abolition-uni"
paginate_path: "blog/page:num/"
permalink: blog/:title/

header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Cultural Studies Association (U.S.) — 19th Annual Conference, 2021
    url: https://www.culturalstudiesassociation.org/conference.html

social:
  github: sgotzler
  twitter: steevegotz

google_analytics: "UA-58263416-1"

disqus:
    shortname:
